#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KodyWyjsciowe {OK=0};
enum StanyMaszyny {BRAK_ROZKAZU=0, CZEKAJ_NA_GRACZA, OBSLUZ_POLE, AI};
enum TypPola {STANDARDOWE=0, START=1, LATWA_ZDOBYCZ=2, DLA_DOBRA_STADA=3, POSILEK=4, UZYTECZNOSC=5, GRANICA=6, WYGNANIE=7, POGRANICZE=8, UDAJ_SIE_NA_WYGNANIE=9, BEZTROSKI_BAOBAB=10};
enum TypyKart {KARTY_LATWEJ_ZDOBYCZY, KARTY_DLA_DOBRA_STADA};

#endif

