#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KodyWyjsciowe {OK=0};
enum StanyMaszyny {BRAK_ROZKAZU=0, CZEKAJ_NA_GRACZA, OBSLUZ_POLE, AI};
enum TypPola {STANDARDOWE=0, START, SZANSA, KASA_PUBLICZNA, PODATEK, UZYTECZNOSC, DWORZEC, WIEZIENIE, ODWIEDZANIE_WIEZIENIA, IDZ_DO_WIEZIENIA};

#endif

