#ifndef TYPY_WYLICZENIOWE_HPP_
#define TYPY_WYLICZENIOWE_HPP_

enum KodyWyjsciowe {OK=0};
enum StanyMaszyny {BRAK_ROZKAZU=0, CZEKAJ_NA_GRACZA, OBSLUZ_POLE, AI};
enum TypPola {STANDARDOWE=0, START=1, SZANSA=2, KASA_PUBLICZNA=3, PODATEK=4, UZYTECZNOSC=5, DWORZEC=6, WIEZIENIE=7, ODWIEDZANIE_WIEZIENIA=8, IDZ_DO_WIEZIENIA=9};

#endif

